export const applicationUi = {
    en: {
        systemUi: {
            loadingPage: 'Loading page...', checkingAccount: 'Checking account...', checkingAdmin: 'Checking administrator access...', checkingProfile: 'Checking profile setup...', accountCheckError: 'Unable to verify your account right now. Please try again.', profileCheckError: 'Unable to verify your profile right now. Please try again.',
            pageNotFound: 'Page not found.', pageNotFoundCopy: 'The address does not match a page in Cane Corso Heritage.', backHome: 'Back to Home',
            languageSelection: 'Language selection', footerNavigation: 'Footer navigation', trademark: 'trademark', visualIdentity: 'Unico Suo Genere visual identity',
            close: 'Close', selectCountry: 'Select country', selectCity: 'Select city', selectCountryFirst: 'Select country first',
        },
        helpPage: {
            topic: 'Help topic', notFound: 'Help topic not found', chooseTopic: 'Choose Explore, Read or Share below to open a supported help topic.',
            exploreTitle: 'Explore the project', exploreText: 'Use the main navigation and the dedicated routes for Stories, Heritage and About USG.',
            readTitle: 'Open full details', readText: 'Story and Heritage details have their own URLs, so they can be opened directly and shared.',
            shareTitle: 'Share a story', shareText: 'Create a Story from your private member area and choose whether it stays private or is shared with the Community.',
        },
        myStories: {
            privateArea: 'Private area', title: 'My Stories', signedInAs: 'Signed in as', introSuffix: 'Keep a Story for yourself or share it with the Community.', myFiles: 'My Files', addStory: '+ Add Story',
            loading: 'Loading your stories...', loadError: 'Unable to load your stories.', refreshError: 'Unable to refresh your stories.', collection: 'Your collection', empty: 'No stories yet.', emptyCopy: 'Your first Story can be private or shared with the Community.', addFirst: 'Add your first Story', storiesLabel: 'Your stories', view: 'View', edit: 'Edit', delete: 'Delete',
            defaultMember: 'USG Member', privateStatus: 'My Own · Private', pendingStatus: 'Community · Pending approval', rejectedStatus: 'Community · Rejected', hiddenStatus: 'Community · Hidden by administrator', approvedStatus: 'Community · Approved',
        },
        storyForm: {
            close: 'Close story form', editKicker: 'Edit Story', addKicker: 'Add Story', editTitle: 'Update your story.', addTitle: 'Share a new story.', intro: 'Choose who can see it, write the text and attach images, audio, MP4 or text documents.',
            visibility: 'Visibility', community: 'Community — visible to everyone', private: 'My Own — only visible to me', title: 'Title', titlePlaceholder: 'A story worth preserving', shortDescription: 'Short description', descriptionPlaceholder: 'A short introduction for the Story card.', story: 'Story', storyPlaceholder: 'Write the Story details.', attachFiles: 'Attach files', fileHint: 'Images, audio, MP4 and text documents · up to 50 MB per file', attachmentVisibility: 'Attachments follow this Story visibility.', publishingAs: 'Publishing as', cancel: 'Cancel', saving: 'Saving...', update: 'Update Story', publish: 'Publish Story', requiredError: 'Please complete all text fields.', saveError: 'Unable to save the story right now.', originalLanguage: 'Original language', languageEnglish: 'English', languageBulgarian: 'Bulgarian', languageItalian: 'Italian', languageHint: 'This marks the language the author is writing in. Machine translations are stored separately and never replace the original.',
        },
        storyDelete: {
            kicker: 'Delete Story', title: 'Remove this story?', copy: 'This story will be removed from the Stories collection.', cancel: 'Cancel', deleting: 'Deleting...', delete: 'Delete Story', error: 'Unable to delete the story right now.',
        },
        myFiles: {
            privateArea: 'Private area', title: 'My Files', intro: 'Upload images, audio, MP4 video or text documents. Keep them private or share them with the Community.', chooseFiles: 'Choose files', visibility: 'Visibility', private: 'My Own — private', community: 'Community — public', uploading: 'Uploading...', upload: 'Upload Files', fileHint: 'Images, audio, MP4 and text documents · up to 50 MB per file', loading: 'Loading your files...', empty: 'No files in your account yet.', filesLabel: 'Your files', zoom: 'Zoom', zoomFile: 'Zoom {name}', audioUnsupported: 'Your browser does not support audio playback.', open: 'Open', public: 'Public', followsStory: 'Visibility follows Story', attachedToStory: 'Attached to a Story', delete: 'Delete', closePreview: 'Close image preview', chooseError: 'Choose at least one file.', loadError: 'Unable to load your files.', uploadError: 'Unable to upload the selected files.', visibilityError: 'Unable to change file visibility.', deleteError: 'Unable to delete this file.', privateStatus: 'My Own · Private', pendingStatus: 'Community · Pending approval', rejectedStatus: 'Community · Rejected', hiddenStatus: 'Community · Hidden by administrator', approvedStatus: 'Community · Approved',
        },
        memberProfile: {
            back: '← Back to Members', loading: 'Loading member profile...', notFound: 'This member profile could not be found.', loadError: 'Unable to load this member profile right now.', profile: 'Member profile', ownBioSetup: 'Your public biography is optional. Complete the required profile setup below first.', ownBioEmpty: 'You have not added a public biography yet.', memberBioEmpty: 'This member has not added a public biography yet.', memberSince: 'Member since {date}', publishedWork: 'Published work', storiesBy: 'Stories by {name}', noStories: 'No published stories from this member yet.', story: 'Story', viewStory: 'View story →', sharedFiles: 'Shared files', filesBy: 'Public files by {name}', noFiles: 'No public files from this member yet.', audioUnsupported: 'Your browser does not support audio playback.', openFile: 'Open file →', defaultMember: 'USG Member', communityEyebrow: 'Community', privateEyebrow: 'My Own',
        },
        admin: {
            navLabel: 'Administration navigation', administration: 'Administration', moderationBadge: 'Moderation v2', backWebsite: '← Back to website', loading: 'Loading administration panel...', loadError: 'Unable to load the administration panel.', actionError: 'The administration action could not be completed.', detailsLoadError: 'Unable to load member details.',
            overview: 'Overview', pendingApprovals: 'Pending approvals', members: 'Members', stories: 'Stories', files: 'Files', ratings: 'Ratings', pending: 'Pending', overviewNote: 'Community Stories and files require administrator approval. Private content remains private and does not enter the moderation queue.', pendingIntro: 'Review new Community material before it becomes public.', noPendingStories: 'No pending Stories.', noPendingFiles: 'No pending files.',
            title: 'Title', author: 'Author', created: 'Created', actions: 'Actions', file: 'File', owner: 'Owner', type: 'Type', member: 'Member', username: 'Username', role: 'Role', account: 'Account', joined: 'Joined', visibility: 'Visibility', moderation: 'Moderation', size: 'Size', noLinkedProfile: 'No linked profile', untitled: 'Untitled', details: 'Details', currentAdmin: 'Current admin', deactivate: 'Deactivate', reactivate: 'Reactivate', deactivateConfirm: '{action} {name}?', deactivated: 'Member deactivated.', reactivated: 'Member reactivated.', memberFallback: 'this member', deactivationNote: 'Deactivation blocks protected account features and write operations. Permanent account deletion is reserved for a separate server-side step.',
            approve: 'Approve', reject: 'Reject', hide: 'Hide', restore: 'Restore', delete: 'Delete', storyApproved: 'Story approved.', storyRejected: 'Story rejected.', storyHidden: 'Story hidden.', storyRestored: 'Story restored and approved.', storyDeleted: 'Story deleted.', fileApproved: 'File approved.', fileRejected: 'File rejected.', fileHidden: 'File hidden.', fileRestored: 'File restored and approved.', fileDeleted: 'File deleted.', rejectStoryConfirm: 'Reject "{name}"?', hideStoryConfirm: 'Hide "{name}" from the Community?', deleteStoryConfirm: 'Permanently delete "{name}" and its attached files?', rejectFileConfirm: 'Reject "{name}"?', hideFileConfirm: 'Hide "{name}" from the Community?', deleteFileConfirm: 'Permanently delete "{name}"?',
            storyRatings: 'Story ratings', noStoryRatings: 'No Story ratings yet.', fileRatings: 'File ratings', noFileRatings: 'No file ratings yet.', memberDetails: 'Member details', closeMemberDetails: 'Close member details', displayName: 'Display name', firstName: 'First name', lastName: 'Last name', country: 'Country', city: 'City', phone: 'Phone', email: 'Email', accountStatus: 'Account status', lastSignIn: 'Last sign-in', emailConfirmed: 'Email confirmed', bio: 'Bio', noBio: 'No bio provided.',
            statusPrivate: 'private', statusCommunity: 'community', statusPending: 'pending', statusApproved: 'approved', statusRejected: 'rejected', statusHidden: 'hidden', statusActive: 'active', statusInactive: 'inactive', statusAdmin: 'admin', statusUser: 'user', statusUnknown: 'unknown',
        },
    },
    bg: {
        systemUi: {
            loadingPage: 'Зареждане на страницата...', checkingAccount: 'Проверка на акаунта...', checkingAdmin: 'Проверка на администраторския достъп...', checkingProfile: 'Проверка на настройката на профила...', accountCheckError: 'В момента акаунтът не може да бъде проверен. Опитайте отново.', profileCheckError: 'В момента профилът не може да бъде проверен. Опитайте отново.',
            pageNotFound: 'Страницата не е намерена.', pageNotFoundCopy: 'Адресът не съответства на страница в Cane Corso Heritage.', backHome: 'Назад към Начало',
            languageSelection: 'Избор на език', footerNavigation: 'Навигация във футъра', trademark: 'търговска марка', visualIdentity: 'Визуална идентичност Unico Suo Genere',
            close: 'Затвори', selectCountry: 'Избери държава', selectCity: 'Избери град', selectCountryFirst: 'Първо избери държава',
        },
        helpPage: {
            topic: 'Тема от помощта', notFound: 'Темата от помощта не е намерена', chooseTopic: 'Избери Разглеждане, Четене или Споделяне по-долу, за да отвориш поддържана тема.',
            exploreTitle: 'Разгледай проекта', exploreText: 'Използвай главната навигация и отделните страници за Истории, Наследство и За USG.',
            readTitle: 'Отвори пълните детайли', readText: 'Историите и материалите от Наследство имат собствени адреси, така че могат да се отварят директно и да се споделят.',
            shareTitle: 'Сподели история', shareText: 'Създай История от личната си зона и избери дали да остане лична или да бъде споделена с Общността.',
        },
        myStories: {
            privateArea: 'Лична зона', title: 'Моите истории', signedInAs: 'Влязъл като', introSuffix: 'Запази История само за себе си или я сподели с Общността.', myFiles: 'Моите файлове', addStory: '+ Добави история',
            loading: 'Зареждане на историите...', loadError: 'Историите ви не могат да бъдат заредени.', refreshError: 'Историите ви не могат да бъдат обновени.', collection: 'Вашата колекция', empty: 'Все още няма истории.', emptyCopy: 'Първата ви История може да бъде лична или споделена с Общността.', addFirst: 'Добави първата си История', storiesLabel: 'Вашите истории', view: 'Виж', edit: 'Редактирай', delete: 'Изтрий',
            defaultMember: 'USG член', privateStatus: 'Само моя · Лична', pendingStatus: 'Общност · Чака одобрение', rejectedStatus: 'Общност · Отхвърлена', hiddenStatus: 'Общност · Скрита от администратор', approvedStatus: 'Общност · Одобрена',
        },
        storyForm: {
            close: 'Затвори формата за История', editKicker: 'Редактиране на История', addKicker: 'Добавяне на История', editTitle: 'Обнови своята История.', addTitle: 'Сподели нова История.', intro: 'Избери кой може да я вижда, напиши текста и прикачи изображения, аудио, MP4 или текстови документи.',
            visibility: 'Видимост', community: 'Общност — видима за всички', private: 'Само моя — видима само за мен', title: 'Заглавие', titlePlaceholder: 'История, която си струва да бъде запазена', shortDescription: 'Кратко описание', descriptionPlaceholder: 'Кратко въведение за картата на Историята.', story: 'История', storyPlaceholder: 'Напиши детайлите на Историята.', attachFiles: 'Прикачи файлове', fileHint: 'Изображения, аудио, MP4 и текстови документи · до 50 MB на файл', attachmentVisibility: 'Прикачените файлове следват видимостта на Историята.', publishingAs: 'Публикува като', cancel: 'Отказ', saving: 'Запазване...', update: 'Обнови Историята', publish: 'Публикувай Историята', requiredError: 'Попълни всички текстови полета.', saveError: 'Историята не може да бъде запазена в момента.', originalLanguage: 'Оригинален език', languageEnglish: 'Английски', languageBulgarian: 'Български', languageItalian: 'Италиански', languageHint: 'Това отбелязва езика, на който авторът пише. Машинните преводи се пазят отделно и никога не заменят оригинала.',
        },
        storyDelete: {
            kicker: 'Изтриване на История', title: 'Да премахнем ли тази История?', copy: 'Историята ще бъде премахната от колекцията с Истории.', cancel: 'Отказ', deleting: 'Изтриване...', delete: 'Изтрий Историята', error: 'Историята не може да бъде изтрита в момента.',
        },
        myFiles: {
            privateArea: 'Лична зона', title: 'Моите файлове', intro: 'Качвай изображения, аудио, MP4 видео или текстови документи. Запази ги лични или ги сподели с Общността.', chooseFiles: 'Избери файлове', visibility: 'Видимост', private: 'Само мои — лични', community: 'Общност — публични', uploading: 'Качване...', upload: 'Качи файловете', fileHint: 'Изображения, аудио, MP4 и текстови документи · до 50 MB на файл', loading: 'Зареждане на файловете...', empty: 'Все още няма файлове в акаунта ви.', filesLabel: 'Вашите файлове', zoom: 'Увеличи', zoomFile: 'Увеличи {name}', audioUnsupported: 'Браузърът ви не поддържа възпроизвеждане на аудио.', open: 'Отвори', public: 'Публичен', followsStory: 'Видимостта следва Историята', attachedToStory: 'Прикачен към История', delete: 'Изтрий', closePreview: 'Затвори прегледа на изображението', chooseError: 'Избери поне един файл.', loadError: 'Файловете ви не могат да бъдат заредени.', uploadError: 'Избраните файлове не могат да бъдат качени.', visibilityError: 'Видимостта на файла не може да бъде променена.', deleteError: 'Файлът не може да бъде изтрит.', privateStatus: 'Само мой · Личен', pendingStatus: 'Общност · Чака одобрение', rejectedStatus: 'Общност · Отхвърлен', hiddenStatus: 'Общност · Скрит от администратор', approvedStatus: 'Общност · Одобрен',
        },
        memberProfile: {
            back: '← Назад към Членове', loading: 'Зареждане на профила...', notFound: 'Профилът на този член не беше намерен.', loadError: 'В момента профилът не може да бъде зареден.', profile: 'Профил на член', ownBioSetup: 'Публичната биография е по желание. Първо попълни задължителните данни за профила по-долу.', ownBioEmpty: 'Все още не сте добавили публична биография.', memberBioEmpty: 'Този член все още не е добавил публична биография.', memberSince: 'Член от {date}', publishedWork: 'Публикувани материали', storiesBy: 'Истории от {name}', noStories: 'Все още няма публикувани истории от този член.', story: 'История', viewStory: 'Виж историята →', sharedFiles: 'Споделени файлове', filesBy: 'Публични файлове от {name}', noFiles: 'Все още няма публични файлове от този член.', audioUnsupported: 'Браузърът ви не поддържа възпроизвеждане на аудио.', openFile: 'Отвори файла →', defaultMember: 'USG член', communityEyebrow: 'Общност', privateEyebrow: 'Само моя',
        },
        admin: {
            navLabel: 'Навигация на администрацията', administration: 'Администрация', moderationBadge: 'Модерация v2', backWebsite: '← Назад към сайта', loading: 'Зареждане на административния панел...', loadError: 'Административният панел не може да бъде зареден.', actionError: 'Административното действие не може да бъде изпълнено.', detailsLoadError: 'Данните за члена не могат да бъдат заредени.',
            overview: 'Преглед', pendingApprovals: 'Чакащи одобрение', members: 'Членове', stories: 'Истории', files: 'Файлове', ratings: 'Оценки', pending: 'Чакащи', overviewNote: 'Историите и файловете за Общността изискват одобрение от администратор. Личното съдържание остава лично и не влиза в опашката за модерация.', pendingIntro: 'Прегледай новия материал за Общността, преди да стане публичен.', noPendingStories: 'Няма чакащи Истории.', noPendingFiles: 'Няма чакащи файлове.',
            title: 'Заглавие', author: 'Автор', created: 'Създадено', actions: 'Действия', file: 'Файл', owner: 'Собственик', type: 'Тип', member: 'Член', username: 'Потребителско име', role: 'Роля', account: 'Акаунт', joined: 'Присъединил се', visibility: 'Видимост', moderation: 'Модерация', size: 'Размер', noLinkedProfile: 'Няма свързан профил', untitled: 'Без заглавие', details: 'Детайли', currentAdmin: 'Текущ администратор', deactivate: 'Деактивирай', reactivate: 'Активирай отново', deactivateConfirm: '{action} {name}?', deactivated: 'Членът е деактивиран.', reactivated: 'Членът е активиран отново.', memberFallback: 'този член', deactivationNote: 'Деактивирането блокира защитените функции на акаунта и операциите за запис. Постоянното изтриване на акаунт е запазено за отделна сървърна стъпка.',
            approve: 'Одобри', reject: 'Отхвърли', hide: 'Скрий', restore: 'Възстанови', delete: 'Изтрий', storyApproved: 'Историята е одобрена.', storyRejected: 'Историята е отхвърлена.', storyHidden: 'Историята е скрита.', storyRestored: 'Историята е възстановена и одобрена.', storyDeleted: 'Историята е изтрита.', fileApproved: 'Файлът е одобрен.', fileRejected: 'Файлът е отхвърлен.', fileHidden: 'Файлът е скрит.', fileRestored: 'Файлът е възстановен и одобрен.', fileDeleted: 'Файлът е изтрит.', rejectStoryConfirm: 'Да се отхвърли ли „{name}“?', hideStoryConfirm: 'Да се скрие ли „{name}“ от Общността?', deleteStoryConfirm: 'Да се изтрие ли окончателно „{name}“ и прикачените файлове?', rejectFileConfirm: 'Да се отхвърли ли „{name}“?', hideFileConfirm: 'Да се скрие ли „{name}“ от Общността?', deleteFileConfirm: 'Да се изтрие ли окончателно „{name}“?',
            storyRatings: 'Оценки на Истории', noStoryRatings: 'Все още няма оценки на Истории.', fileRatings: 'Оценки на файлове', noFileRatings: 'Все още няма оценки на файлове.', memberDetails: 'Детайли за члена', closeMemberDetails: 'Затвори детайлите за члена', displayName: 'Показвано име', firstName: 'Име', lastName: 'Фамилия', country: 'Държава', city: 'Град', phone: 'Телефон', email: 'Имейл', accountStatus: 'Статус на акаунта', lastSignIn: 'Последен вход', emailConfirmed: 'Имейлът е потвърден', bio: 'Биография', noBio: 'Няма предоставена биография.',
            statusPrivate: 'лично', statusCommunity: 'общност', statusPending: 'чака одобрение', statusApproved: 'одобрено', statusRejected: 'отхвърлено', statusHidden: 'скрито', statusActive: 'активен', statusInactive: 'неактивен', statusAdmin: 'администратор', statusUser: 'потребител', statusUnknown: 'неизвестен',
        },
    },
    it: {
        systemUi: {
            loadingPage: 'Caricamento pagina...', checkingAccount: 'Verifica account...', checkingAdmin: 'Verifica accesso amministratore...', checkingProfile: 'Verifica configurazione profilo...', accountCheckError: 'Impossibile verificare l’account in questo momento. Riprova.', profileCheckError: 'Impossibile verificare il profilo in questo momento. Riprova.',
            pageNotFound: 'Pagina non trovata.', pageNotFoundCopy: 'L’indirizzo non corrisponde a una pagina di Cane Corso Heritage.', backHome: 'Torna alla Home',
            languageSelection: 'Selezione lingua', footerNavigation: 'Navigazione piè di pagina', trademark: 'marchio', visualIdentity: 'Identità visiva Unico Suo Genere',
            close: 'Chiudi', selectCountry: 'Seleziona paese', selectCity: 'Seleziona città', selectCountryFirst: 'Seleziona prima il paese',
        },
        helpPage: {
            topic: 'Argomento di aiuto', notFound: 'Argomento di aiuto non trovato', chooseTopic: 'Scegli Esplora, Leggi o Condividi qui sotto per aprire un argomento supportato.',
            exploreTitle: 'Esplora il progetto', exploreText: 'Usa la navigazione principale e le pagine dedicate a Storie, Heritage e Su USG.',
            readTitle: 'Apri i dettagli completi', readText: 'Le Storie e i contenuti Heritage hanno URL propri, quindi possono essere aperti direttamente e condivisi.',
            shareTitle: 'Condividi una storia', shareText: 'Crea una Storia dalla tua area privata e scegli se mantenerla privata o condividerla con la Comunità.',
        },
        myStories: {
            privateArea: 'Area privata', title: 'Le mie Storie', signedInAs: 'Accesso come', introSuffix: 'Conserva una Storia per te o condividila con la Comunità.', myFiles: 'I miei file', addStory: '+ Aggiungi Storia',
            loading: 'Caricamento delle tue Storie...', loadError: 'Impossibile caricare le tue Storie.', refreshError: 'Impossibile aggiornare le tue Storie.', collection: 'La tua raccolta', empty: 'Nessuna Storia.', emptyCopy: 'La tua prima Storia può essere privata o condivisa con la Comunità.', addFirst: 'Aggiungi la tua prima Storia', storiesLabel: 'Le tue Storie', view: 'Vedi', edit: 'Modifica', delete: 'Elimina',
            defaultMember: 'Membro USG', privateStatus: 'Solo mia · Privata', pendingStatus: 'Comunità · In attesa di approvazione', rejectedStatus: 'Comunità · Rifiutata', hiddenStatus: 'Comunità · Nascosta dall’amministratore', approvedStatus: 'Comunità · Approvata',
        },
        storyForm: {
            close: 'Chiudi modulo Storia', editKicker: 'Modifica Storia', addKicker: 'Aggiungi Storia', editTitle: 'Aggiorna la tua Storia.', addTitle: 'Condividi una nuova Storia.', intro: 'Scegli chi può vederla, scrivi il testo e allega immagini, audio, MP4 o documenti di testo.',
            visibility: 'Visibilità', community: 'Comunità — visibile a tutti', private: 'Solo mia — visibile solo a me', title: 'Titolo', titlePlaceholder: 'Una storia che merita di essere conservata', shortDescription: 'Breve descrizione', descriptionPlaceholder: 'Una breve introduzione per la scheda della Storia.', story: 'Storia', storyPlaceholder: 'Scrivi i dettagli della Storia.', attachFiles: 'Allega file', fileHint: 'Immagini, audio, MP4 e documenti di testo · fino a 50 MB per file', attachmentVisibility: 'Gli allegati seguono la visibilità della Storia.', publishingAs: 'Pubblicazione come', cancel: 'Annulla', saving: 'Salvataggio...', update: 'Aggiorna Storia', publish: 'Pubblica Storia', requiredError: 'Completa tutti i campi di testo.', saveError: 'Impossibile salvare la Storia in questo momento.', originalLanguage: 'Lingua originale', languageEnglish: 'Inglese', languageBulgarian: 'Bulgaro', languageItalian: 'Italiano', languageHint: 'Indica la lingua in cui scrive l’autore. Le traduzioni automatiche vengono salvate separatamente e non sostituiscono mai l’originale.',
        },
        storyDelete: {
            kicker: 'Elimina Storia', title: 'Rimuovere questa Storia?', copy: 'La Storia verrà rimossa dalla raccolta Storie.', cancel: 'Annulla', deleting: 'Eliminazione...', delete: 'Elimina Storia', error: 'Impossibile eliminare la Storia in questo momento.',
        },
        myFiles: {
            privateArea: 'Area privata', title: 'I miei file', intro: 'Carica immagini, audio, video MP4 o documenti di testo. Mantienili privati o condividili con la Comunità.', chooseFiles: 'Scegli file', visibility: 'Visibilità', private: 'Solo miei — privati', community: 'Comunità — pubblici', uploading: 'Caricamento...', upload: 'Carica file', fileHint: 'Immagini, audio, MP4 e documenti di testo · fino a 50 MB per file', loading: 'Caricamento dei tuoi file...', empty: 'Non ci sono ancora file nel tuo account.', filesLabel: 'I tuoi file', zoom: 'Ingrandisci', zoomFile: 'Ingrandisci {name}', audioUnsupported: 'Il browser non supporta la riproduzione audio.', open: 'Apri', public: 'Pubblico', followsStory: 'La visibilità segue la Storia', attachedToStory: 'Allegato a una Storia', delete: 'Elimina', closePreview: 'Chiudi anteprima immagine', chooseError: 'Scegli almeno un file.', loadError: 'Impossibile caricare i tuoi file.', uploadError: 'Impossibile caricare i file selezionati.', visibilityError: 'Impossibile modificare la visibilità del file.', deleteError: 'Impossibile eliminare questo file.', privateStatus: 'Solo mio · Privato', pendingStatus: 'Comunità · In attesa di approvazione', rejectedStatus: 'Comunità · Rifiutato', hiddenStatus: 'Comunità · Nascosto dall’amministratore', approvedStatus: 'Comunità · Approvato',
        },
        memberProfile: {
            back: '← Torna ai Membri', loading: 'Caricamento profilo membro...', notFound: 'Questo profilo membro non è stato trovato.', loadError: 'Impossibile caricare questo profilo in questo momento.', profile: 'Profilo membro', ownBioSetup: 'La biografia pubblica è facoltativa. Completa prima i dati obbligatori del profilo qui sotto.', ownBioEmpty: 'Non hai ancora aggiunto una biografia pubblica.', memberBioEmpty: 'Questo membro non ha ancora aggiunto una biografia pubblica.', memberSince: 'Membro da {date}', publishedWork: 'Contenuti pubblicati', storiesBy: 'Storie di {name}', noStories: 'Non ci sono ancora Storie pubblicate da questo membro.', story: 'Storia', viewStory: 'Vedi Storia →', sharedFiles: 'File condivisi', filesBy: 'File pubblici di {name}', noFiles: 'Non ci sono ancora file pubblici di questo membro.', audioUnsupported: 'Il browser non supporta la riproduzione audio.', openFile: 'Apri file →', defaultMember: 'Membro USG', communityEyebrow: 'Comunità', privateEyebrow: 'Solo mia',
        },
        admin: {
            navLabel: 'Navigazione amministrazione', administration: 'Amministrazione', moderationBadge: 'Moderazione v2', backWebsite: '← Torna al sito', loading: 'Caricamento pannello di amministrazione...', loadError: 'Impossibile caricare il pannello di amministrazione.', actionError: 'Impossibile completare l’azione amministrativa.', detailsLoadError: 'Impossibile caricare i dettagli del membro.',
            overview: 'Panoramica', pendingApprovals: 'Approvazioni in attesa', members: 'Membri', stories: 'Storie', files: 'File', ratings: 'Valutazioni', pending: 'In attesa', overviewNote: 'Le Storie e i file della Comunità richiedono l’approvazione di un amministratore. I contenuti privati restano privati e non entrano nella coda di moderazione.', pendingIntro: 'Controlla il nuovo materiale della Comunità prima che diventi pubblico.', noPendingStories: 'Nessuna Storia in attesa.', noPendingFiles: 'Nessun file in attesa.',
            title: 'Titolo', author: 'Autore', created: 'Creato', actions: 'Azioni', file: 'File', owner: 'Proprietario', type: 'Tipo', member: 'Membro', username: 'Username', role: 'Ruolo', account: 'Account', joined: 'Iscritto', visibility: 'Visibilità', moderation: 'Moderazione', size: 'Dimensione', noLinkedProfile: 'Nessun profilo collegato', untitled: 'Senza titolo', details: 'Dettagli', currentAdmin: 'Amministratore attuale', deactivate: 'Disattiva', reactivate: 'Riattiva', deactivateConfirm: '{action} {name}?', deactivated: 'Membro disattivato.', reactivated: 'Membro riattivato.', memberFallback: 'questo membro', deactivationNote: 'La disattivazione blocca le funzioni protette dell’account e le operazioni di scrittura. L’eliminazione permanente dell’account è riservata a un passaggio server separato.',
            approve: 'Approva', reject: 'Rifiuta', hide: 'Nascondi', restore: 'Ripristina', delete: 'Elimina', storyApproved: 'Storia approvata.', storyRejected: 'Storia rifiutata.', storyHidden: 'Storia nascosta.', storyRestored: 'Storia ripristinata e approvata.', storyDeleted: 'Storia eliminata.', fileApproved: 'File approvato.', fileRejected: 'File rifiutato.', fileHidden: 'File nascosto.', fileRestored: 'File ripristinato e approvato.', fileDeleted: 'File eliminato.', rejectStoryConfirm: 'Rifiutare “{name}”?', hideStoryConfirm: 'Nascondere “{name}” dalla Comunità?', deleteStoryConfirm: 'Eliminare definitivamente “{name}” e i file allegati?', rejectFileConfirm: 'Rifiutare “{name}”?', hideFileConfirm: 'Nascondere “{name}” dalla Comunità?', deleteFileConfirm: 'Eliminare definitivamente “{name}”?',
            storyRatings: 'Valutazioni Storie', noStoryRatings: 'Nessuna valutazione delle Storie.', fileRatings: 'Valutazioni file', noFileRatings: 'Nessuna valutazione dei file.', memberDetails: 'Dettagli membro', closeMemberDetails: 'Chiudi dettagli membro', displayName: 'Nome visualizzato', firstName: 'Nome', lastName: 'Cognome', country: 'Paese', city: 'Città', phone: 'Telefono', email: 'Email', accountStatus: 'Stato account', lastSignIn: 'Ultimo accesso', emailConfirmed: 'Email confermata', bio: 'Biografia', noBio: 'Nessuna biografia fornita.',
            statusPrivate: 'privato', statusCommunity: 'comunità', statusPending: 'in attesa', statusApproved: 'approvato', statusRejected: 'rifiutato', statusHidden: 'nascosto', statusActive: 'attivo', statusInactive: 'inattivo', statusAdmin: 'amministratore', statusUser: 'utente', statusUnknown: 'sconosciuto',
        },
    },
};
